### ISSUE TITLE
ToolsPro v0.0.2 To-Do

### ISSUE THREAD

**Issue by Pub4Game** [NukkitRu/ToolsPro#1]
What will be added in the new version:
- [ ] The new system of invisibility(/vanish)
- [x] Support multi languages. Thank you very much @fromgate and @mik2212 for their important contribution to ToolsPro!
- [x] Bug fixes

**Comment by Pub4Game** [comment]
@Angelic47 Could you suggest how I can do /vanish? The effect is not very good, and hidePlayer does not work if any player go to the server

**Comment by Angelic47** [comment]
@Pub4Game Sorry but I didn't notice your message until just now... In my opinion, nukkit will call a method (sorry I forget the name of it) which send player entities to new player, so you can't modify it directlly. But I think it's better to create an variable like HashTable or ArrayList, when new players join, then hide all players for himself who are in this variable.

**Comment by Pub4Game** [comment]
Hmm... Thanks
